### ISSUE TITLE
Removing factors

### ISSUE THREAD

**Issue by sstevens2** [datacarpentry/r-intro-geospatial#119]
This might be covered by #78 but thought I would explicitly suggest it.  Need to update since in R4.0.0+ `read.csv` has `stringsAsFactors=FALSE` by default.

I suggest removing the factors section in the [Data Structures episode](https://datacarpentry.org/r-intro-geospatial/03-data-structures-part1/index.html) and removing the factors section in the [Exploring Data Frames episode](https://datacarpentry.org/r-intro-geospatial/04-data-structures-part2/index.html). I think both of those sections should lift right out.

If factors are needed for the [Raster and Vector lesson](https://datacarpentry.org/r-raster-vector-geospatial/), then I would suggest still removing them from [Exploring Data Frames](https://datacarpentry.org/r-intro-geospatial/04-data-structures-part2/index.html) but keeping them in [Data Structures](https://datacarpentry.org/r-intro-geospatial/03-data-structures-part1/index.html)

**Comment by albhasan** [comment]
Good morning.

I would like to provide some context to this issue. I only found 6 references to 'stringsAsFactors' in this leson.

The first two are in the script `./renv/activate.R` lines 299 and 561. I'm not an user of the `renv` package, but I think we can safely remove those as they are set to FALSE (R's default since v4). Besides, the readers aren't supposed to read this script.

The next one is in `./episodes/03-data-structures-part1.Rmd` line 412 and it's part of the solution to challenge 3. It makes no difference because it's also set to FALSE. However, that challenge description makes sense from the perspective of R v3. I guess we could update or remove challenge 3.

The next 3 appear in `./episodes/04-data-structures-part2.Rmd` lines 73, 348, and 369.

In line 73, `stringAsFactors` is set to TRUE and it includes a comment explainign the readers the default value of this property changed from R v3 to R v4. Besides, this line sets up data which is needed by a different task below. This was made so to ensure the code runs on R v4 while minimizing the changes to this lesson's contents. This is the change that would require more attention.

In lines 348 and 369 `stringsAsFactors` is set to FALSE and they can be safely removed.

Bests,

**Comment by albhasan** [comment]
Status update. After @mikemahoney218 PR #145, there is only one remaining instance of ```read.csv``` using ```stringsAsFactors = TRUE```: It is in lesson "Exploring Data Frames" (lesson 4, line 73). This line of code includes a comment explaining that we need factors later in the lesson, precisely because this lesson explains factors.

Besides, I read this [document](https://cran.r-project.org/doc/manuals/r-devel/NEWS.html) (referenced [here)](https://github.com/datacarpentry/r-intro-geospatial/issues/119#issuecomment-1331304744) and I couldn't find any statement saying that ```stringsAsFactors``` is going to be removed from R.

For this reason, I propose we close this issue.

**Comment by mikemahoney218** [comment]
Sounds good to me!
