### ISSUE TITLE
"Remove column" & "Remove row" section belong to "Subsetting Data" lesson?

### ISSUE THREAD

**Issue by kokbent** [datacarpentry/r-intro-geospatial#18]
http://www.datacarpentry.org/r-intro-geospatial/05-data-structures-part2/

Section on removing column & removing row should be part of "subsetting data" which comes in next lesson. Awkward to introduce `cats[-4,]` syntax without first going through what `cats[4,]` mean. Likewise, it's also awkward to do `drop <- names(cats) %in% c("age"); cats[,!drop]` without any explanation on what is `%in%` and what's the rationale behind `!drop`.

**Comment by lachlandeer** [comment]
Good call, and probably worth changing... 

I'll label this as 'help wanted' - feel free to take a stab at this yourself if you'd like.

**Comment by ErinBecker** [comment]
Thanks @kokbent for your attention to detail. I'm trying to make the changes you suggest here, but having difficultly seeing exactly where the issue is referring to. I think this issue is referring to the episode that is now [Episode 4](https://datacarpentry.org/r-intro-geospatial/04-data-structures-part2/index.html), but the current version of the lessons doesn't have any reference to "cats", or well . . . it does

![screen shot 2018-07-10 at 2 30 14 pm](https://user-images.githubusercontent.com/19176319/42538798-c9f7468c-844d-11e8-9263-cc8c91b14d71.png)

But this appears to be a stray comment left over from an earlier version of the lesson before it was using gapminder. (??) There are no other references to "cats" in this episode. 

Your main comment seems to be about introducing negative subsetting before introducing subsetting syntax generally. I think the offending line is: 

![screen shot 2018-07-10 at 2 31 45 pm](https://user-images.githubusercontent.com/19176319/42538899-1c451216-844e-11e8-9fd7-ccd47bc06995.png)

As you said, the next episode [Subsetting Data](https://datacarpentry.org/r-intro-geospatial/05-data-subsetting/index.html) goes through subsetting, including negative indexing, in depth. Maybe we can just remove everything in the "Removing columns" and "Removing rows" sections. Any seconds? @janu123 @lachlandeer @juanfung

**Comment by lachlandeer** [comment]
Hi @ErinBecker 

I agree with this, let's cut it.
