### ISSUE TITLE
Check for redundancies

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/r-intro-geospatial#2]
This lesson will be taught as the first lesson in the Geospatial workshop. The [raster-vector](https://github.com/datacarpentry/r-raster-vector-geospatial) lessons will be taught later in the workshop. Go through the [raster-vector](https://github.com/datacarpentry/r-raster-vector-geospatial) lessons and remove things that are redundant with this repo.

**Comment by lachlandeer** [comment]
Hi @ErinBecker @lwasser @tyson-swetnam 

I've looked over both the `r-intro` material and the `r-raster-vector` lesson and thought about what materials to keep for the intro. Before we progress on doing it, I think a broad consensus on what to have would be useful so that we are all on the same page.

One burning question I have is whether we want to move away from some of the traditional R syntax like `gsub`, `subset` which appear in later lessons of `r-raster-vector` and move towards more `tidyverse` grammar from `dplyr` and `tidyr` - I personally would like that and it's a bit more 'modern', but it is an only an opinion. If we do the lessons included in this workshop would change. Below I propose two alternative lesson schemes, one that would emphasize tidyverse grammar and one that doesn't.

## On Lessons to Keep - a Proposal
If we *do not* move to the `tidyverse` grammar; from it looks like we need material from the following lessons:

* 01-rstudio-intro.Rmd
* 02-project-intro.Rmd
* 03-seeking-help.Rmd
* 04-data-structures-part1.Rmd
* 05-data-structures-part2.Rmd
* 06-data-subsetting.Rmd
* 07-control-flow.Rmd
* 08-plot-ggplot2.Rmd
* 11-writing-data.Rmd (potentially switch to readr::read_csv / readr::write_csv rather than `R`'s builtin)

If we *do* want to move to tidyverse grammar, it looks like we would need the following (if we want to keep this repo as a self contained reference for everything in the `raster-vector` lesson)

* 01-rstudio-intro.Rmd
* 02-project-intro.Rmd
* 03-seeking-help.Rmd
* 04-data-structures-part1.Rmd
* 05-data-structures-part2.Rmd
* 06-data-subsetting.Rmd
* 07-control-flow.Rmd
* 08-plot-ggplot2.Rmd
* 11-writing-data.Rmd (potentially switch to readr::read_csv / readr::write_csv rather than `R`'s builtin)
* 13-dplyr.Rmd
* 14-tidyr.Rmd

## On Data
Are we going to stick with the `gapminder` data for the r-intro? Or would we potentially switch to data that comes from the same region as the geospatial data so that everything is more coherent (eg - data from states, counties in the area). Alternatively some of the data from the time series part of the raster-vector lesson could be appropriate

That's a lot to digest - Interested in everyone's thoughts. Might be worth spinning the data choice into a seperate issue if we want to have a longer discussion.

**Comment by lwasser** [comment]
This is great! thank you @lachlandeer 

Based on our  notes from previous discussions:
https://github.com/datacarpentry/curriculum-advisors/blob/master/geospatial/minutes/march-2018-geospatial-minutes.md 

Here is my two cents. This is really too many lessons. The geospatial lessons take more than 2 days as they are if you want to teach them WELL. As such, i suggest before we dive into details we do the following:

1. identify learning goals of this lesson set
2. suggest the bare bones things people will need to dive into the geospatial stuff.
3. consider whether we can use data in the geospatial lessons to do this (i suspect we can) so we dont have to increase cognitive load with a new dataset (gapminder)... altho it is COOL!

Notes below from our discussions of the new organization

```
    Repo 1:
        modified from https://github.com/datacarpentry/r-spatial-data-management-intro/
        Episode 1: Spatial data formats
            file types
                vector file types, what is a shapefile, what is a geojson object
                raster file types
                geospatial databases?
                geographic and projected coordinate systems - what they are, why they matter, how to select them
        Episode 2: Project organization and management
            some from https://github.com/datacarpentry/r-spatial-data-management-intro/blob/master/_episodes_rmd/02-spatial-data-formats.Rmd
        Episode 3: Spatial data landscape

    Repo 2: Introduction to R for Spatial Data
        modified from https://github.com/swcarpentry/r-novice-gapminder (episodes 1-6?)

    Repo 3: Raster and Vector Lesson
        modified from https://github.com/datacarpentry/R-spatial-raster-vector-lesson
```

Learning goals

1. introduce audience to the core elements of R
* variables
* core data structures like data.frame (could open the spreadsheet of veg height data in the geospatial lessons to achieve this)

2. Introduce people to R studio / projects
* r studio interface
* working directories 

With these goals in mind, i think this less set can be VERY VERY short! we will teach ggplot when we teach plotting. And things like dplyr and such could come up in those geospatial lessons too.

if this is a 4 day workshop we won't get to the spatial stuff! :)

So at the most i thijnk the first 4-6 lessons of gapminder could cover it. And maybe look to see if we can just use the tree height data to be consistent. let's keep this to 2-3 hours MAX. but 1 - 1.5 hours is better.

thoughts? @jsta  @chris-prener @tyson-swetnam i can't seem to ping anne ? is she not on this repo yet perhaps? 

So without looking closely at all of the lessons (time crunched today) at the most i'd teach
```
01-rstudio-intro.Rmd
02-project-intro.Rmd
03-seeking-help.Rmd
04-data-structures-part1.Rmd
05-data-structures-part2.Rmd
06-data-subsetting.Rmd
```
but honestly i probably wouldn't teach that much as a lot of it you can teach in the geospatial lessons!!

**Comment by lwasser** [comment]
actually it looks like a really important lesson was cut maybe?? or maybe i just created it after and never added it to the lesson set or maybe i'm losing it :) 

https://github.com/datacarpentry/r-raster-vector-geospatial/blob/master/_episodes_rmd/11-vector-raster-integration.Rmd

normally when i teach this you extract the values -- then you bring in data in a spreadsheet for comparison and create a scatter plot. This is where data.frames and dplyr can be useful 

https://earthdatascience.org/courses/earth-analytics/remote-sensing-uncertainty/import-summarize-tree-height-data/ 

the above lesson is how that goes... so what we could do in this lesson set is just manipulate the spreadsheet data potentially... and maybe the scatterplot becomes a bonus lesson if there's time. but atleast the data are relevant to the spatial data taught.

**Comment by jsta** [comment]
I agree with increasing the use of `dplyr`. The current state of the lessons reflect the fact that this was not possible with the old `sp` workflow.

**Comment by lachlandeer** [comment]
Thanks for your opinion @lwasser 

The motivation for having extra lessons there was that it keeps content self contained, and teaches `dplyr`, `ggplot` etc without the geospatial spin - it might be an easier first pass if someone with less experience is attending/looking over it.

My thoughts were to have the lessons there and available (even if supplementary so they are not actually taught live). But I would be happy to cut them out (it's less work).

Also agree that the tree height data or similar are a good alternative data set.

@jsta : should we work towards moving everthying to `dplyr` &`tidyr` also in the `r-raster-vector` lesson? If so we might want to create an issue there and reference this discussion

**Comment by lwasser** [comment]
totally i think we want to keep this lesson set light. Then link to lessons on extra content that may be relevant.  (like the r ecology lessons!)

i second the dplyr additions too!!! great suggestion and @jsta  is totally on point with the comment above!! let's create an issue

**Comment by ErinBecker** [comment]
Closing based on https://github.com/datacarpentry/r-intro-geospatial/issues/22 and discussion there.
