### ISSUE TITLE
install.packages() in Episode 1 or not?

### ISSUE THREAD

**Issue by rmdickson** [datacarpentry/r-intro-geospatial#64]
install.packages() is mentioned in the Questions and the Key Points for Episode 1, but never actually used.  It ought to be demonstrated somewhere, but I don't yet know where it would go best.  (I will only be teaching this lesson for the first time a few days from now.)

Or if install.packages() doesn't appropriately belong anywhere, then it should be removed from the Questions and Key Points.

**Comment by jsta** [comment]
Agreed. What do you think about moving this info to the `dplyr` lesson (number 6) because that material uses `install.packages`? 

This is tricky because on one hand we hope learners can install packages prior to the workshop but in practice this is not always the case. Instructors almost need to decide during the workshop itself whether having a demo of package installation is necessary.

**Comment by lachlandeer** [comment]
Might we be able to add a section at the end of episode one on packages/libraries and then use this as a place to install `dplyr` and `ggplot2`?

We can then link this across episodes as appropriate?

**Comment by sheilasaia** [comment]
@lachlandeer @jsta I'm happy to start working on this at the end of episode one! 😄
